<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\PhotoEvidenceController;
use Illuminate\Support\Facades\Route;

// ─── PUBLIC ROUTES ────────────────────────────────────────
Route::get('/', [HomeController::class, 'index'])->name('home');
Route::post('/search', [HomeController::class, 'search'])->name('home.search');

// ─── AUTH ROUTES (generated by Breeze) ────────────────────
require __DIR__.'/auth.php';

// ─── PROTECTED ROUTES ─────────────────────────────────────
Route::middleware(['auth'])->group(function () {

    Route::get('/dashboard', fn() => view('dashboard'))->name('dashboard');

    // Users CRUD
    Route::resource('users', UserController::class);

    // Archived orders (must be before resource to avoid conflict)
    Route::get('orders/archived', [OrderController::class, 'archived'])
         ->name('orders.archived');
    Route::patch('orders/{id}/restore', [OrderController::class, 'restore'])
         ->name('orders.restore');

    // Orders CRUD
    Route::resource('orders', OrderController::class);

    // Photo upload
    Route::post('orders/{order}/photos', [PhotoEvidenceController::class, 'store'])
         ->name('orders.photos.store');
});